environment: default
spring:
  config:
    activate:
      on-profile: def
name: default-YAML
server:
  port: 5000
myCustomVarTree:
  welcomeMsg: Hello
enabled: true

---
environment: testing
spring:
  config:
    activate:
      on-profile: test
name: test-YAML
server:
  port: 4000
myCustomVarTree:
  welcomeMsg: Hello from Test
enabled: true
---
environment: production
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
server:
  port: 7070
myCustomVarTree:
  welcomeMsg: Hello from Pr
enabled: true